### PR TITLE
Fixed and refactored the repairs minigame

### LINKED ISSUE #72: Fix Repair minigame

### PR DESCRIPTION
**Pull request by maxwellpark**

### CODE REVIEW

File: Assets/Scripts/Minigames/ShipRepairs/GreenZone.cs [hunk 1]
```diff
@@ -14,7 +14,8 @@ private void Start()
     // Call this to increase the difficulty 
     public void ReduceSize()
     {
-        transform.localScale += new Vector3(-RepairsConstants.sizeDecrease, 0f, 0f); 
+        transform.localScale += new Vector3(
```
Comment (ambid17) [inline Assets/Scripts/Minigames/ShipRepairs/GreenZone.cs:17]: why not just use -=

**Review by ambid17 — APPROVED** [review]

File: Assets/Scripts/Minigames/ShipRepairs/GreenZone.cs (hunk 1 above)
Comment (maxwellpark) [reply Assets/Scripts/Minigames/ShipRepairs/GreenZone.cs:17]: honestly i normally do it this way 
no idea why and cant really be bothered it to change it
